version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    networks:
      ncnetwork:
        ipv4_address: ${MYSQL_HOST}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        #MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  app:
    image: nextcloud-fpm:latest
    restart: always
      #ports:
      #- "9000:9000"
    depends_on:
      - db
    networks:
      ncnetwork:
        ipv4_address: ${NEXTCLOUD_HOST}
    volumes:
      - nextcloud_data:${NEXTCLOUD_DATADIR}
      - nextcloud_config:/var/www/nextcloud/config/
      - nextcloud_apps:/var/www/nextcloud/apps/
      - nextcloud_db:/var/www/nextcloud/db/
      - nextcloud_source:/var/www/nextcloud/

  web:
    image: nginx:latest
    restart: always
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      ncnetwork:
        ipv4_address: ${NGINX_HOST}
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./sites-enabled/nc-server.conf:/etc/nginx/sites-enabled/nc-server.conf:ro
      - ./tls:/etc/nginx/tls:ro
      - nextcloud_source:/var/www/nextcloud/
      - nextcloud_data:${NEXTCLOUD_DATADIR}
    depends_on:
      - app

volumes:
  db_data:
  nextcloud_data:
    driver_opts:
      type: none
      device: ${NEXTCLOUD_MOUNT}
      o: bind
  nextcloud_config:
  nextcloud_apps:
  nextcloud_db:
  nextcloud_source:

networks:
  ncnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

